# Generated by Django 5.1.4 on 2025-02-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ph_number', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('booked', 'Booked')], default='available', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
